name: Metrics

on:
  # Update daily at 06:00 IST
  schedule:
    - cron: '30 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: noiseless47
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          config_display: large
          config_theme: dark
          config_output: png
          filename: metrics.png
          output_action: commit
          committer_branch: main
          committer_message: "chore(metrics): update metrics"

          # Languages
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_sections: most-used
          plugin_languages_limit: 10
          plugin_languages_ignored: html, css

          # Calendar / activity
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # Follow-up (issues/PRs)
          plugin_followup: yes
          plugin_followup_sections: repositories

          # Achievements (compact)
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes

          # Habits (lightweight charts)
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
